#!/usr/bin/env bash
set -e

useradd --uid 10011001 --home-dir /home/aiblocks --no-log-init aiblocks \
    && mkdir -p /home/aiblocks \
    && chown -R aiblocks:aiblocks /home/aiblocks

mkdir -p /opt/aiblocks/bin
mkdir -p /opt/aiblocks/www
chown -R aiblocks:aiblocks /opt/aiblocks/www
mkdir -p /opt/aiblocks/postgresql/data
